### PR TITLE
ssh over $http_proxy

### PR DESCRIPTION
**Pull request by mattn**
This change make be possible to connect to labstack server with ssh via http_proxy.

### CODE REVIEW

**Comment by vishr** [comment]
@mattn thanks for your contribution 🎉

**Comment by vishr** [comment]
@mattn I tried it with [mitmproxy](https://mitmproxy.org) and [squid](http://www.squid-cache.org), both results me with the following error

`2018/04/02 20:54:01 4 cannot open new session: ssh: handshake failed: ssh: overflow reading version string`

Can you take a look?

**Comment by mattn** [comment]
What string do you set for $http_proxy?

**Comment by vishr** [comment]
I used `export http_proxy=http://localhost:8080`

**Comment by mattn** [comment]
Do your proxy server support CONNECT method?

**Comment by mattn** [comment]
The error seems to be appear if the first response from server was not `SSH-`.

**Comment by vishr** [comment]
That's true, do you know any proxy server to test?

**Comment by vishr** [comment]
Okay, I even tried `tinyproxy` but all of them gives the same error.

**Comment by mattn** [comment]
I tested this on https://github.com/elazarl/goproxy

**Comment by mattn** [comment]
I installed tinyproxy and can reproduce it. I'll look into it.

**Comment by vishr** [comment]
Perfect, we should at least make it work with the popular proxy servers.

**Comment by mattn** [comment]
I could connect to labstack.me:22 with modify /etc/tinyproxy/tinyproxy.conf. Added `ConnectPort 22`.

**Comment by mattn** [comment]
I could connect with squid with modify /etc/squid/squid.conf.

* added `acl localnet src ....`
* added `acl Safe_ports port 22`
* comment out following lines.

```
# Deny CONNECT to other than secure SSL ports
#http_access deny CONNECT !SSL_ports
```

**Comment by vishr** [comment]
@mattn Thanks for investigation, I will put it in the docs. On a side note, where do you think this feature is useful? In most of the organization you will not have control over the proxy configuration. Please feel free to comment.

**Comment by mattn** [comment]
In my office, port 22 is allowed to connect over proxy. Or we can connect via ssh-tunneling. For example, using [sslh](http://www.rutschle.net/tech/sslh/README.html).

**Comment by vishr** [comment]
How about SSH over 443, is that allowed?

**Comment by mattn** [comment]
Yes, it is allowed in my office. When CONNECT method is accepted in the transport, it should be behaved as native socket. So not related on SSH.

**Pull request merged**
